version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /worker
    schedule:
      interval: monthly
    groups:
      worker-development:
        patterns:
          - "*"
